# Requires variable instance_name


- name: Collect list of CA certificates
  command: dsconf {{ instance_name }} security ca-certificate list 
  register: server_ca_cert_list

- name: configure CA certificate when not found
  block:

     - name: copy CA cert to {{ instance_name }} host
       copy:
         src: /tmp/rh423-ca.crt
         dest: /tmp/rh423-ca.crt
         owner: student
         group: student
         mode: 0664

     - name: import CA cert
       command: dsconf {{ instance_name }} security ca-certificate add --file /tmp/rh423-ca.crt --name RH423CA

     - name: set the trust options for the ca cert
       command: dsconf {{ instance_name }} security ca-certificate set-trust-flags --flags "CT,," RH423CA

  when: server_ca_cert_list.stdout.find('RH423CA') == -1
