
- name: push LDIF files to RHDS
  copy:
    src: Files/"{{ item }}"
    dest: /tmp/
  loop: "{{ modify_ldifs }}"
  when: modify_ldifs is defined

- name: modify (add, change, delete) entries with each LDIF file.
  command: ldapmodify -c -x -D "cn=Directory Manager" -w RedHat123 -f /tmp/{{ item }}
  loop: "{{ modify_ldifs }}"
  when: modify_ldifs is defined

- name: delete recursively portions of the tree
  command: ldapdelete -c -x -D "cn=Directory Manager" -w RedHat123 -r {{ item }}
  loop: "{{ delete_dns }}"
  when: delete_dns is defined


