#For later chapters (monitoring and tuning) to use.

- name: Add entries from managing groups and roles
  import_playbook: manage_roles_solve.yml

- name: Add user account entries with passwords
  import_playbook: client_users_solve.yml

- name: Perform several queries on the documents to populate statistics
  hosts: servera
  vars:
      ldap_uri: ldap://rhds.lab.example.com
  tasks:
      - name: ensure openldap-clients on servera
        dnf:
           name: openldap-clients
           state: present

     - name: Add ACIs to ou=Douments tree
       import_tasks: Tasks/manage_entries.yml
       vars:
         modify_ldifs:
            - add_access_aci.ldif

      - name: run ldapsearch commands
        command: ldapsearch -x -H {{ ldap_uri }} {{ item }}
        loop:
           - 'documentTitle~=Red Hat Directory Installation'
           - 'documentTitle~=Red Hat Directory Performance'
           - 'documentTitle~=Red Hat Directory Deployment'
           - 'documentAuthor~=dballard documentTitle'
           - 'documentAuthor~=mmuehlfeld documentTitle'
           - 'documentTitle~=Red Hat Directory'

