---
# Optional variables in Tasks/managed_entries: 
# modify_ldifs delete_dns add_entries_ldifs 

- name: Cleanup after Entries LAB in rhds-ldap-manage-entries finish
  hosts: rhds
  tasks:
     - name: remove authors and document entries from directory.
       import_tasks: Tasks/manage_entries.yml
       vars:
         modify_ldifs:
            - delete_docs.ldif
         delete_dns:
            - ou=Documents,dc=lab,dc=example,dc=com

