---
- name: remove replica1 instance 
  hosts: replica1
  vars:
     instance_name: replica1
  tasks:
    # consider options to determine any existing instance_name from system

    - name: stop and remove the instance
      block:
        - name: stop the instance
          command: 'dsctl {{ instance_name }} stop'
          ignore_errors: true

        - name: remove the instance
          command: 'dsctl {{ instance_name }} remove --do-it'
          ignore_errors: true
      
    - name: remove packages
      import_tasks: Tasks/remove_packages.yml

    - name: remove packages
      import_tasks: Tasks/close_firewall.yml


