---

- name: Create Certificate Authority on workstation
  import_playbook: create_ca.yml

- name: tasks to "solve" managing certificates GE rhds-manage-certs
  hosts: rhds
  vars:
    instance_name: rh423
  tasks:

    - name: configure CA certificate in instance
      import_tasks: Tasks/add_CA_to_instance.yml
      
    - name: configure CA Trust Database on host
      import_tasks: Tasks/update_ca_trust.yml

    - name: Replace server cert
      block:

        - name: look for existin server cert
          command: dsconf {{ instance_name }} security certificate list 
          register: server_cert_list

        - name: fail if not found
          assert: 
            that: server_cert_list.stdout.find('rhds-cert') != -1
            success_msg: server cert appears to exist, no need to replace.
            fail_msg: server cert does not exist, continue to creating CSR

      rescue:

        - name: generate a CSR
          command: dsctl rh423 tls generate-server-cert-csr -s "CN=rhds.lab.example.com"

        - name: sign and update certificate
          import_tasks: Tasks/sign_replace_cert.yml
          vars:
            cert_nick: rhds-cert
         
  
  handlers:
     - name: restart_instance
       command: dsctl {{ instance_name }} restart

